
# Speedtest Data of Philippines - Datasets from Ookla, GADM Maps and NTC

### Import libraries to be used for this project: numpy, pandas and geopandas

In [1]:
from datetime import datetime

import geopandas as gp
import pandas as pd
import numpy as np
import sweetviz as sv

### Load the Philippine Boundaries from GADM.org as a GeoDataFrame (DataFrame with geometry column). For this project, we are going to use the Shapefile with Provinces Layer. We checked the DataFrame for null values and found no null values on the NAME_1 and geometry columns which is going to be used to be merged later with the Ookla data

In [2]:
pinas = gp.GeoDataFrame.from_file("gadm36_PHL_shp.zip", layer="gadm36_PHL_1")
pinas

,GID_0,NAME_0,GID_1,NAME_1,VARNAME_1,NL_NAME_1,TYPE_1,ENGTYPE_1,CC_1,HASC_1,geometry
0,PHL,Philippines,PHL.1_1,Abra,None,None,Lalawigan|Probinsya,Province,1401,PH.AB,"POLYGON ((120.77473 17.16318, 120.76637 17.159..."
1,PHL,Philippines,PHL.2_1,Agusan del Norte,None,None,Lalawigan|Probinsya,Province,1602,PH.AN,"POLYGON ((125.44627 8.66631, 125.44199 8.66333..."
2,PHL,Philippines,PHL.3_1,Agusan del Sur,None,None,Lalawigan|Probinsya,Province,1603,PH.AS,"POLYGON ((125.90923 7.99845, 125.90176 7.99794..."
3,PHL,Philippines,PHL.4_1,Aklan,None,None,Lalawigan|Probinsya,Province,604,PH.AK,"MULTIPOLYGON (((122.42083 11.63194, 122.42000 ..."
4,PHL,Philippines,PHL.5_1,Albay,None,None,Lalawigan|Probinsya,Province,505,PH.AL,"MULTIPOLYGON (((123.28764 13.04923, 123.28686 ..."
...,...,...,...,...,...,...,...,...,...,...,...
76,PHL,Philippines,PHL.77_1,Tawi-Tawi,None,None,Lalawigan|Probinsya,Province,1570,PH.TT,"MULTIPOLYGON (((119.46694 4.58694, 119.46639 4..."
77,PHL,Philippines,PHL.78_1,Zambales,None,None,Lalawigan|Probinsya,Province,155,PH.PN,"MULTIPOLYGON (((120.08285 14.75048, 120.08222 ..."
78,PHL,Philippines,PHL.79_1,Zamboanga del Norte,None,None,Lalawigan|Probinsya,Province,972,PH.ZN,"MULTIPOLYGON (((122.09467 7.53152, 122.09467 7..."
79,PHL,Philippines,PHL.80_1,Zamboanga del Sur,None,None,Lalawigan|Probinsya,Province,973,PH.ZS,"MULTIPOLYGON (((122.29816 6.87506, 122.29816 6..."
80,PHL,Philippines,PHL.81_1,Zamboanga Sibugay,None,None,Lalawigan|Probinsya,Province,983,PH.ZY,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7..."

In [3]:
pinas.isnull().sum()

GID_0         0
NAME_0        0
GID_1         0
NAME_1        0
VARNAME_1    78
NL_NAME_1    81
TYPE_1        0
ENGTYPE_1     0
CC_1          0
HASC_1        0
geometry      0
dtype: int64

# Load the data from Ookla for Mobile Broadband. For this project, we are going to use a single file from a quarter of the year 2020 for the purpose of simulating the process. We also checked for nulls in this DataFrame and found no nulls.

In [4]:
q4m2020 = gp.GeoDataFrame.from_file("2020-10-01_performance_mobile_tiles.zip")
print(q4m2020.head())
print(q4m2020.shape)

            quadkey  avg_d_kbps  avg_u_kbps  avg_lat_ms  tests  devices  \
0  1322033110323033       34134       19585          21    150       55
1  3100103010200101       12566        6215          33     21       13
2  1202310022300211       78967       15661          16      3        2
3  1202303220333332       79228       21851          21     42       27
4  1231210130113111       26073       10918          29     42       25

                                            geometry
0  POLYGON ((100.78308 13.60862, 100.78857 13.608...
1  POLYGON ((104.79309 -2.98693, 104.79858 -2.986...
2  POLYGON ((17.06726 48.09276, 17.07275 48.09276...
3  POLYGON ((14.40308 45.34056, 14.40857 45.34056...
4  POLYGON ((75.58044 31.31610, 75.58594 31.31610...
(4197854, 7)

In [5]:
q4m2020.isnull().sum()

quadkey       0
avg_d_kbps    0
avg_u_kbps    0
avg_lat_ms    0
tests         0
devices       0
geometry      0
dtype: int64

### Join the Ookla Datasets with Philippine Boundaries to get the geometries of Philippine Provinces with at least 1 tile.

In [6]:
ph_q4m2020 = gp.sjoin(pinas[['NAME_1','geometry']], q4m2020, how="inner", predicate='intersects')
print(ph_q4m2020.head())
print(ph_q4m2020.shape)

  NAME_1                                           geometry  index_right  \
0   Abra  POLYGON ((120.77473 17.16318, 120.76637 17.159...      2964587
0   Abra  POLYGON ((120.77473 17.16318, 120.76637 17.159...      2189991
0   Abra  POLYGON ((120.77473 17.16318, 120.76637 17.159...      2874385
0   Abra  POLYGON ((120.77473 17.16318, 120.76637 17.159...      1881482
0   Abra  POLYGON ((120.77473 17.16318, 120.76637 17.159...      1450375

            quadkey  avg_d_kbps  avg_u_kbps  avg_lat_ms  tests  devices
0  1323012311231230       16750        4748          21      1        1
0  1323012311221330        7071        2259          29      1        1
0  1323012311230121        4199        3853          32      1        1
0  1323012311232021        4117        8335          26      4        4
0  1323012311232030       11697       12815          31      8        4
(51616, 9)

In [8]:
ph_q4m2020.isnull().sum()

NAME_1         0
geometry       0
index_right    0
quadkey        0
avg_d_kbps     0
avg_u_kbps     0
avg_lat_ms     0
tests          0
devices        0
dtype: int64

### Next step would be to merge the data with the list of provinces and regions to in order to match a certain province to its corresponding region.

In [13]:
phregions = pd.read_excel("Regions.xlsx")
phregions

                 NAME_1       Region
0                   NaN          NaN
1                  Abra          CAR
2      Agusan del Norte  Region XIII
3        Agusan del Sur  Region XIII
4                 Aklan    Region VI
..                  ...          ...
78             Zambales   Region III
79  Zamboanga del Norte    Region IX
80    Zamboanga del Sur    Region IX
81    Zamboanga Sibugay    Region IX
82  Metropolitan Manila          NCR

[83 rows x 2 columns]

In [16]:
ph_q4m2020_regions = pd.merge(ph_q4m2020,phregions, on="NAME_1", how="inner")
ph_q4m2020_regions

,NAME_1,geometry,index_right,quadkey,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices,Region
0,Abra,"POLYGON ((120.77473 17.16318, 120.76637 17.159...",2964587,1323012311231230,16750,4748,21,1,1,CAR
1,Abra,"POLYGON ((120.77473 17.16318, 120.76637 17.159...",2189991,1323012311221330,7071,2259,29,1,1,CAR
2,Abra,"POLYGON ((120.77473 17.16318, 120.76637 17.159...",2874385,1323012311230121,4199,3853,32,1,1,CAR
3,Abra,"POLYGON ((120.77473 17.16318, 120.76637 17.159...",1881482,1323012311232021,4117,8335,26,4,4,CAR
4,Abra,"POLYGON ((120.77473 17.16318, 120.76637 17.159...",1450375,1323012311232030,11697,12815,31,8,4,CAR
...,...,...,...,...,...,...,...,...,...,...
50420,Zamboanga Sibugay,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7...",1542059,1323213121120310,4059,1930,32,2,1,Region IX
50421,Zamboanga Sibugay,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7...",1289953,1323213121120120,9130,2857,30,1,1,Region IX
50422,Zamboanga Sibugay,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7...",1799778,1323213121103211,3026,5431,51,46,8,Region IX
50423,Zamboanga Sibugay,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7...",1751169,1323213120012130,5941,3108,37,2,2,Region IX
50424,Zamboanga Sibugay,"MULTIPOLYGON (((122.85805 7.27653, 122.85837 7...",3646047,1323213123013031,34681,2266,29,3,1,Region IX

### We added columns to convert the average upload and download speeds from KBPS to MBPS for the purpose of data simplification.

In [17]:
ph_q4m2020_regions['avg_d_mbps'] = ph_q4m2020_regions['avg_d_kbps'] / 1000
ph_q4m2020_regions['avg_u_mbps'] = ph_q4m2020_regions['avg_u_kbps'] / 1000
ph_q4m2020_regions.head()
ph_q4m2020_regions.shape

(50425, 12)

### We used groupby "Region" to further simplify the data into regions, and aggregate statistics to get the Mean of Upload Speed, Download Speeds and Latency, and the Sum of Number of Tests and Devices per Province. Using the aggregate function also drops the unnecessary columns in the process such as geometry and index columns and would only return specified columns in the expression. We then renamed the columns for proper presentation using array and rename function.

In [20]:
d = {'tests': 'Tests (Q4-2020)', 'devices': 'Devices (Q4-2020)', 'avg_lat_ms':'Ave Latency(ms) (Q4-2020)','avg_d_mbps':'Ave Download(Mbps) (Q4-2020)','avg_u_mbps':'Ave Upload(Mbps) (Q4-2020)'}
ph_q4m2020_regions_grp = ph_q4m2020_regions.groupby('Region').agg({'tests':'sum', 'devices':'sum','avg_lat_ms':'mean','avg_d_mbps':'mean', 'avg_u_mbps':'mean'}).rename(columns=d)
ph_q4m2020_regions_grp

,Tests (Q4-2020),Devices (Q4-2020),Ave Latency(ms) (Q4-2020),Ave Download(Mbps) (Q4-2020),Ave Upload(Mbps) (Q4-2020)
Region,,,,,
ARMM,7692,2318,57.160615,7.108765,5.169553
CAR,10623,4184,45.540373,8.091913,4.459382
NCR,285695,117799,24.708185,28.887553,6.562790
Region I,23843,9585,33.952587,12.259604,4.932170
Region II,15396,6305,38.583815,10.890773,5.177189
Region III,104467,42178,32.145979,14.219295,5.146316
Region IV-A,170788,68019,34.004543,14.223361,4.909055
Region IV-B,11018,3847,39.927649,10.162448,5.668466
Region IX,12194,4020,46.117424,10.746596,6.254332
Region V,24125,9561,42.824761,10.425221,5.576936
Region VI,40470,15343,60.213000,10.188891,5.343674
Region VII,72541,24854,46.150476,11.826433,5.546191
Region VIII,21294,7155,55.028609,8.579837,5.519151
Region X,23238,7224,46.058046,11.665935,6.379092
Region XI,38654,11566,47.631512,12.277664,5.743927
Region XII,10128,3714,46.162698,10.645325,6.142450
Region XIII,11525,3539,50.142857,9.576202,5.506749

In [21]:
ph_q4m2020_regions_grp.to_csv("ph_q4m2020_regions_grp.csv")
ph_q4m2020_regions_grp.dtypes

Tests (Q4-2020)                   int64
Devices (Q4-2020)                 int64
Ave Latency(ms) (Q4-2020)       float64
Ave Download(Mbps) (Q4-2020)    float64
Ave Upload(Mbps) (Q4-2020)      float64
dtype: object